### ISSUE TITLE
Unable to resolve practicalmeteor:chai

### ISSUE THREAD

**Issue by ddeklerk** [clayne11/eslint-import-resolver-meteor#8]
After some messing around I finally got this package working, but there is still at least one package that is not correctly recognized. That is `practicalmeteor:chai`.

Here is the import statement:
`import { assert } from 'meteor/practicalmeteor:chai';`

And this is the error that I get:
`Unable to resolve path to module 'meteor/practicalmeteor:chai'  import/no-unresolved`

**Comment by clayne11** [comment]
Is `practicalmeteor:chai` in your `.meteor/packages` file? If so, can you post your repo so I can look at it and try to fix it?

**Comment by ddeklerk** [comment]
I just found out it is not in my `.meteor/packages` file. It is however a dependency of `practicalmeteor:mocha`, so I did not need to install it separately. Adding `practicalmeteor:chai` seems to have fixed it. Perhaps the `.meteor/versions` file should also be checked for installed packages?

Oh, and I found the same problem to occur with `aldeed:simple-schema`, which is a dependency of `aldeed:collection2`.

**Comment by clayne11** [comment]
We had a discussion about that in #1 and decided that it makes more sense to be explicit and use `.meteor/packages` except for internal Meteor packages where we use `.meteor/versions`. I also outlined the strategy in the `README`.

The reasoning is that implicit dependencies are somewhat "magical", and it's much easier to reason about and debug explicitly defined dependencies rather than implied dependencies. For those two packages I would simply recommend adding them directly to your project.

**Comment by ddeklerk** [comment]
Ah, I see. And yes, that is what I ended up doing.
